---
title: "data-cleaning"
output: html_document
date: '2022-04-04'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(data.table)
library(lubridate)
library(openxlsx)
library(readxl)
library(janitor)
```
```{r}
# clean 2019 april file specifically - extra field
# april2019 <- data.table(read_excel("../inputs/data/bus/ttc-bus-delay-data-2019.xlsx", 4))
# 
# april2019[, `Incident ID`:= NULL]
# head(april2019)
# write.xlsx(april2019, "../inputs/data/bus/ttc-bus-delay-data-2019-updated.xlsx", overwrite = TRUE, sheetName = 'Apr 2019')
# year2019 <- data.table(read_excel("../inputs/data/bus/ttc-bus-delay-data-2019.xlsx", 4))

# get all files in bus directory
file_list <- list.files("../inputs/data/bus")
# for each file in dir:
#   for each sheet in file:
#     append to df list
#   merge all months in list to single df
# merge years if you want
df_list <- list()

# for each file = for each year
for (i in 1:length(file_list)) {
  filename <- sprintf("../inputs/data/bus/%s", file_list[i])
  sheetnames <- getSheetNames(filename)
  sub_df_list <- list()
  
  # for each sheet = for each month
  for (j in 1:length(sheetnames)) {
    # if (sheetnames[i] == 'Apr 2019' && file_list[i] == 'ttc-bus-delay-data-2019.xlsx') {
    #   df <- data.table(read_excel(filename, j))
    #   df[, `Incident ID`:= NULL]
    # }
    df <- data.table(read_excel(filename, j))
    # df[, `Report Date` := as.Date(`Report Date`)]
    df[, Time := format(Time, format = "%H:%M:%S")]
    df <- clean_names(df)
    sub_df_list[[j]] <- df
  }
  
  df_year <- rbindlist(sub_df_list, fill = TRUE)
  
  df_list[[i]] <- df_year
}

```

# EXPLORATORY CLEANING - DO NOT NEED TO RUN
Skip ahead to **FINAL CLEANING CHUNK** 

#### Checking NAs
```{r}
na_list <- list()

for (i in 1:length(df_list)) {
  na_rows <- sum(!complete.cases(df_list[[i]]))
  all_rows <- count(df_list[[i]])
  na_list[i] <- na_rows / all_rows
}

na_list
```

2018 NAs
```{r}
df_2019 <- copy(df_list[[6]])

df_2019

df_2019[, .N]

df_2019[, c('incident_id', 'delay', 'gap', 'vehicle', 'direction', 'location', 'min_gap', 'incident') := NULL]
sum(!complete.cases(df_2019))
df_2019[complete.cases(df_2019), mean(min_delay), by=day][order(-V1)]

df_2019[!complete.cases(df_2019)]

```


```{r}
# 15-20% rows have NAs; check their distributions before dropping
df_2014 <- df_list[[1]]

df_2014

df_2014_na <- df_2014[rowSums(is.na(df_2014)) > 0, ] 

df_2014_na[rowSums(is.na(df_2014_na)) > 0, ] # 15k rows with a null value

df_2014_na[, vehicle :=NULL]
df_2014_na[, direction :=NULL]

df_2014_na[rowSums(is.na(df_2014_na)) > 0, ] # 158 rows with null value

df_2014_na[complete.cases(df_2014_na), mean(min_delay), by=incident][order(-V1)]
df_2014[complete.cases(df_2014), mean(min_delay), by=incident][order(-V1)]

df_2014[complete.cases(df_2014), mean(min_delay), by=day][order(-V1)]
```
```{r}
# plot delay by route
for (i in 1:length(df_list)) {
  year_df <- copy(df_list[[i]])
  year_df <- year_df[, route := as.character(route)]
  year_df <- year_df[, c('route', 'min_delay')]
  p <- year_df[complete.cases(year_df), mean(min_delay), by=route] %>%
    ggplot(aes(x= reorder(route,-V1), y=V1)) + 
    geom_bar(stat="identity") 
  plot(p)
}

# looks like a few routes are delayed much more often - bad data or reality? explore

# plot delay by day
for (i in 1:length(df_list)) {
  year_df <- copy(df_list[[i]])
  year_df <- year_df[, route := as.character(route)]
  year_df <- year_df[, c('day', 'min_delay')]
  p <- year_df[complete.cases(year_df), mean(min_delay), by=day] %>%
    ggplot(aes(x= reorder(day,-V1), y=V1)) + 
    geom_bar(stat="identity") 
  plot(p)
}

# plot delay by incident
for (i in 1:length(df_list)) {
  year_df <- copy(df_list[[i]])
  year_df <- year_df[, c('incident', 'min_delay')]
  p <- year_df[complete.cases(year_df), mean(min_delay), by=incident] %>%
    ggplot(aes(x= reorder(incident,-V1), y=V1)) + 
    geom_bar(stat="identity") 
  plot(p)
}
```


```{r}
for (i in 1:length(df_list)) {
  df <- df_list[[i]][,.SD, .SDcols = !c('vehicle', 'direction')]
  print(df[complete.cases(df), mean(min_delay), by=day][order(-V1)])
}
```


```{r}
df_list[[1]]

df_incident <- copy(df_list[[1]])
df_incident[, week := week(report_date)]
df_incident[
    complete.cases(df_incident) 
    & report_date != as.POSIXct("2014-03-01", tz="UTC") 
    & incident != 'Diversion', 
  mean(min_delay), by=list(week, incident)] %>%
    ggplot(aes(x=week, y=V1, group=incident, color=incident)) +
    geom_line()



# typeof(df_diversion[3, 1][[1]])
# df_diversion[3, 1][[1]]
# 
# timeframe <- c("2014-03-01")  
# df_diversion[report_date != as.POSIXct("2014-03-01", tz="UTC")]
# df_diversion[report_date == as.double.POSIXlt('2014-03-01')]
```
#### Binding all years together to see a delay trend
```{r}
df_all_years <- copy(rbindlist(df_list, fill = TRUE))

head(df_all_years[complete.cases(df_all_years)])

df_all_years[, month_year := format(as.Date(df_all_years$report_date), "%Y-%m")]
df_all_years <- df_all_years[, c('month_year', 'min_delay', 'incident')]
df_all_years[
    complete.cases(df_all_years) & incident != 'Diversion', 
    mean(min_delay), 
    by=list(month_year, incident)] %>%
    ggplot(aes(x=month_year, y=V1, group=incident, color=incident)) +
    geom_line()

# delay times are slightly increasing actually - this is surprising
# segment growth by routes?
```
```{r}
df_all_years <- copy(rbindlist(df_list, fill = TRUE))
# head(df_all_years)

# exploration box
# df_all_years[!is.na(date) & is.na(report_date), ]
# df_all_years[, .N]
# 
# df_all_years[is.na(vehicle), .N]

####################################################################################v

# min delay outliers
df_all_years[min_delay < 100] %>%
  ggplot(aes(x=min_delay)) + 
  geom_histogram()

df_all_years[min_delay > 995 & min_delay < 1000] %>%
  ggplot(aes(x=min_delay)) + 
  geom_histogram()

df_all_years[min_delay == 999, .N]
df_all_years[min_delay == 998, .N]

quantile(df_all_years[, min_delay], prob=c(.25, .5, .75, .9, .98))
```

# FINAL CLEANING CHUNK
```{r}
# drop incident_id column - only present in 1 month (5k out of 517k total rows)
df_all_years[, incident_id := NULL] 

# drop vehicle column (80k nulls, individual vehicle registrations so very granular)
df_all_years[, vehicle := NULL] 

# cast delay and gap to min_delay and min_gap where the latter is null
df_all_years[!is.na(delay) & is.na(min_delay), min_delay := delay]
df_all_years[!is.na(gap) & is.na(min_gap), min_gap := gap]
# drop delay and gap columns
df_all_years[, delay := NULL] 
df_all_years[, gap := NULL] 

# cast line to route, drop line
df_all_years[!is.na(line) & is.na(route), route := line]
df_all_years[, line := NULL] 

# cast bound to direction, drop bound
df_all_years[!is.na(bound) & is.na(direction), direction := bound]
df_all_years[, bound := NULL] 

# cast date to report_date, drop date
df_all_years[!is.na(date) & is.na(report_date), report_date := date]
df_all_years[, date := NULL] 

# drop remaining rows with NA (~17.5k rows)
df_all_years <- df_all_years[complete.cases(df_all_years)]

# ~500k remaining rows
df_all_years[, .N]

# removing outliers
# quantile(df_all_years[, min_delay], prob=c(.25, .5, .75, .9, .98, .99, .995))
df_all_years <- df_all_years[min_delay <= 235]

# save to RData
saveRDS(df_all_years, file = '../inputs/bus-clean.RDS')
```


# rough work below - no need to run
```{r}
df_list[[1]][, month(`Report Date`)]

df_list[[1]][, mean(`Min Delay`), by=list(Incident, month(`Report Date`))][order(-V1)]

df_list[[1]][, mean(min_delay), by=incident]

mean(df_list[[1]][incident=='Diversion', min_delay][1:10])

df_list[[1]]
```

