---
title: "data-exploration"
output: html_document
date: '2022-04-07'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(data.table)
library(lubridate)
library(rcompanion)
library(AICcmodavg)
library(Rmisc)
```

# Load data
```{r}
df <- readRDS('../inputs/bus-clean.RDS')

head(df)
```

# some more cleaning of the incident type
```{r}
incidents <- unique(df[, incident])
incidents

df[incident %like% "^Late Leaving Garage", incident := "Late Leaving Garage"]
df[incident %like% "^Road Block", incident := "Road Block"]
df[incident %like% "^Cleaning", incident := "Cleaning"]
df[incident %like% "^Late Entering Service", incident := "Late Entering Service"]
df[incident %like% "^Operations", incident := "Operations"]
df[incident %like% "^Collision", incident := "Collision"]
df[incident %like% "^Late Leaving Garage", incident := "Late Leaving Garage"]
df[incident == "Securitty", incident := "Security"]
df[incident == "Utilized Off Route", incident := "Diversion"]
df[incident %in% c("Held By", "Late", "Overhead"), incident := "General Delay"]
```


# Summary stats / data characteristics
## Delay over time
```{r}
df[, month_year := format(as.Date(df$report_date), "%Y-%m")]

df[, year := format(as.Date(df$report_date), "%Y")]

df[, mean(min_delay), by=month_year] %>%
    ggplot(aes(x=month_year, y=V1, group=1)) +
    geom_line() 

for (curr_incident in incidents) {
  p <- df[incident == curr_incident, mean(min_delay), by=month_year] %>%
    ggplot(aes(x=month_year, y=V1, group=1)) +
    geom_line() +
    ggtitle(curr_incident)
  
  plot(p)
}

```


## Delay by day of week
```{r}
# TODO: reorder by day of week
df[, mean(min_delay), by=day] %>%
    ggplot(aes(x= reorder(day,c('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday')), y=V1)) + 
    geom_bar(stat="identity") 
```
# Quick modelling
## Check distribution of delays
```{r}
# exploration, no need to run
df %>%
  ggplot(aes(x=min_delay)) + 
  geom_histogram()

delay <- df[, min_delay]
qqnorm(delay, ylab="Quantiles for delay")
qqline(delay, col="red") # clearly right skewed

# applying log transformation
delay_log = log(delay)
delay_log <- delay_log[!is.infinite(delay_log)]
plotNormalHistogram(delay_log)
```


```{r}
# apply this to the actual data frame
df[, delay_log := log(min_delay)]
df <- df[!is.infinite(delay_log)]

# trying to cast the hour out
df[, hour := substr(time, 1, 2)] # keep as character because categorical
head(df)
```



```{r}
df2015 <- df[report_date %between% c('2015-01-01', '2015-12-31')]
length(unique(df2015[, route]))

length(df[, day])
length(df[, delay_log])

model <- lm(delay_log ~ day + incident + hour, data = df2015) 
anova(model) # show results
summary(model)
plot(model)

two_way_day_incident <- aov(delay_log ~ day + incident, data = df) 
two_way_day_hour <- aov(delay_log ~ day + hour, data = df)
two_way_incident_hour <- aov(delay_log ~ hour + incident, data = df)

interaction_day_incident <- aov(delay_log ~ day * incident, data = df)
interaction_day_hour <- aov(delay_log ~ day * hour, data = df)
interaction_incident_hour <- aov(delay_log ~ hour * incident, data = df)

combine_day_incident_plus_hour <- aov(delay_log ~ day * incident + hour, data = df)
combine_incident_hour_plus_day <- aov(delay_log ~ day + incident * hour, data = df)
combine_day_hour_plus_incident <- aov(delay_log ~ day * hour + incident, data = df)

model.set <- list(
  two_way_day_incident, 
  two_way_day_hour, 
  two_way_incident_hour, 
  interaction_day_incident, 
  interaction_day_hour, 
  interaction_incident_hour, 
  combine_day_incident_plus_hour, 
  combine_incident_hour_plus_day,
  combine_day_hour_plus_incident
)

model.names <- c(
  'two_way_day_incident', 
  'two_way_day_hour', 
  'two_way_incident_hour', 
  'interaction_day_incident', 
  'interaction_day_hour', 
  'interaction_incident_hour', 
  'combine_day_incident_plus_hour', 
  'combine_incident_hour_plus_day',
  'combine_day_hour_plus_incident'
)

aic_table <- aictab(model.set, modnames = model.names)
aic_table <- data.table(aic_table)

saveRDS(aic_table, file = '../inputs/aic-table.RDS')
```
```{r}
summary(combine_incident_hour_plus_day)
tukey_output <- TukeyHSD(combine_incident_hour_plus_day)
tukey_output <- data.table(tukey_output)

head(tukey_output)
tukey_output[[1]]

saveRDS(tukey_output[[1]], file = '../inputs/tukey-table.RDS')
```

# plots for results
```{r}
sumstats = summarySE(df,
                measurevar="min_delay",
                groupvars=c("incident"))
sumstats

pd = position_dodge(.2)

sumstats %>% ggplot(aes(x=factor(incident), y=min_delay)) + 
  geom_bar(stat="identity", fill="blue", width=0.8) +
  geom_errorbar(aes(ymin=min_delay-se, ymax=min_delay+se), width=.2, colour='red') +
  xlab("Incident") +
  ylab("Delay (minutes)") + 
  theme(axis.text.x = element_text(angle=90, hjust=1))

df %>% ggplot(aes(x = incident, y = min_delay)) +
  geom_boxplot() + 
  theme(axis.text.x = element_text(angle=90, hjust=1))
```

## hour plots
```{r}
df %>%
  ggplot(aes(x=hour, y=min_delay)) + 
  # geom_errorbar(aes(ymin=min_delay-se, ymax=min_delay+se), width=.2, colour='red') +
  stat_summary(fun.y = "mean", geom = "bar")


df %>% ggplot(aes(x = hour, y = min_delay)) +
  geom_boxplot() + 
  theme(axis.text.x = element_text(angle=90, hjust=1))
```

## day plot
```{r}
df %>% ggplot(aes(x = day, y = min_delay)) +
  geom_boxplot() + 
  theme(axis.text.x = element_text(angle=90, hjust=1))



out <- boxplot.stats(df$min_delay)$out
out_ind <- which(df$min_delay %in% c(out))
df[out_ind, .N] / df[, .N]
```


## anova for delay over time using month-year
```{r}
month_year_aov <- aov(delay_log ~ month_year, data = df)
summary(month_year_aov)

df[, mean(min_delay), by=month_year] %>%
    ggplot(aes(x=month_year, y=V1, group=1)) +
    geom_line() 

year_aov <- aov(delay_log ~ year, data = df)
summary(year_aov)

year_model <- lm(V1 ~ as.numeric(year), data = df[, mean(min_delay), by=year])
summary(year_model)


df[, mean(min_delay), by=year] %>%
    ggplot(aes(x=year, y=V1, group=1)) +
    geom_line() + 
    geom_smooth(method='lm', formula= y~x)

df[incident=='Mechanical', mean(min_delay), by=year] %>%
    ggplot(aes(x=year, y=V1, group=1)) +
    geom_line() + 
    geom_smooth(method='lm', formula= y~x)

df[incident=='Cleaning', mean(min_delay), by=year] %>%
    ggplot(aes(x=year, y=V1, group=1)) +
    geom_line() +
    geom_smooth(method='lm', formula= y~x)


# show some were flat e.g. late leaving garage flat until 2021
year_aov_llg <- aov(delay_log ~ year, data = df[incident=='Late Leaving Garage' & year != 2021])
summary(year_aov_llg)

df[incident=='Late Leaving Garage' & year != 2021] %>% ggplot(aes(x = year, y = min_delay)) +
  geom_boxplot() + 
  theme(axis.text.x = element_text(angle=90, hjust=1))

df[incident=='Late Leaving Garage', mean(min_delay), by=year] %>%
    ggplot(aes(x=year, y=V1, group=1)) +
    geom_line() 

TukeyHSD(year_aov_llg)
```

## worst routes
```{r}
df[, mean(min_delay), by=route][order(-V1)][1:100]

# worst delayed
df[, mean(min_delay), by=route][order(-V1)][1:25] %>%
    ggplot(aes(x= reorder(route,-V1), y=V1)) + 
    geom_bar(stat="identity") # are these night buses?

# least delayed
df[, mean(min_delay), by=route][order(V1)][1:30] %>%
    ggplot(aes(x= reorder(route,V1), y=V1)) + 
    geom_bar(stat="identity") 

df[, mean(min_delay), by=route] %>%
    ggplot(aes(x= reorder(route,-V1), y=V1)) + 
    geom_bar(stat="identity") 
```




# rough work below
```{r}
qqnorm(residuals(model),
       ylab="Sample Quantiles for residuals")

plot(fitted(model),
     residuals(model))

model_day <- lm(delay_log ~ day, data = df2015)
summary(model_day)

model_incident <- lm(delay_log ~ incident, data = df2015)
summary(model_incident)
anova(model_incident)
plot(model_incident)

df2015 %>%
  ggplot(aes(x=incident, y=min_delay)) + 
  geom_bar(stat="identity") 

df2015[incident == 'Mechanical'] %>%
  ggplot(aes(x=day, y=min_delay)) + 
  stat_summary(fun.y = "mean", geom = "bar")

df2015[incident == 'Mechanical'] %>%
  ggplot(aes(x=hour, y=min_delay)) + 
  stat_summary(fun.y = "mean", geom = "bar")

df2015 %>%
  ggplot(aes(x=hour, y=min_delay)) + 
  # geom_bar(stat="identity") 
  stat_summary(fun.y = "mean", geom = "bar")

df2015[hour == '14', sum(min_delay)]
```

